# 基础镜像
FROM  openjdk:17
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /app
# 创建目录
RUN mkdir -p /app
# 指定路径
WORKDIR /app
# 复制jar文件到路径
COPY ./jar/hoho-auth.jar /app/hoho-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","hoho-auth.jar"]