# 基础镜像
FROM nginx
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /nginx/html
# 创建目录
RUN mkdir -p /nginx/html
# 指定路径
WORKDIR /nginx/html
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /nginx/html
