# 基础镜像
FROM  openjdk:17
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /app
# 创建目录
RUN mkdir -p /app
# 指定路径
WORKDIR /app
# 复制jar文件到路径
COPY ./jar/hoho-visual-monitor.jar /app/hoho-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","hoho-visual-monitor.jar"]